In [1]:
# Importing the necessary Libraries to load the data
import fastf1 as f1
import pandas as pd

### **Phase 1 and Phase 2: Project Architecture and Data Ingestion**

Loading a sample Session from 2024 British Grand Prix to get the following data.
1. Lap Data
2. Telemetry
3. Weather
4. Pit Stops
5. Sector Times
6. Race Results

In [17]:
# Importing the data and putting it into cache
f1.Cache.enable_cache("cache_data")
session_BrGP24 = f1.get_session(2024, "Silverstone", "R")
session_BrGP24.load()

Request for URL https://raw.githubusercontent.com/theOehrly/f1schedule/master/schedule_2024.json failed; using cached response
Traceback (most recent call last):
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests_cache\session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests_cache\session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastf1\req.py", line 110, in send
    lim.limit()
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastf1\req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
Request for URL https://api.jolpi.ca/ergast/f1/2024/12/results.json failed; using cached response
Traceback (most recent call last):
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests_cache\session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests_cache\session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastf1\req.py", line 110, in send
    lim.limit()
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastf1\req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 10)
Request for URL https://api.jolpi.ca/ergast/f1/2024/12/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests_cache\session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests_cache\session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastf1\req.py", line 110, in send
    lim.limit()
  File "c:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastf1\req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h

In [8]:
# Lap Data
laps_BrGP24 = session_BrGP24.laps
laps_BrGP24.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:59:51.778000,HAM,44,0 days 00:01:36.034000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:37.703000,...,True,Mercedes,0 days 00:58:15.512000,2024-07-07 14:03:12.541,1,2.0,False,,False,False
1,0 days 01:01:23.198000,HAM,44,0 days 00:01:31.420000,2.0,1.0,NaT,NaT,0 days 00:00:29.249000,0 days 00:00:37.314000,...,True,Mercedes,0 days 00:59:51.778000,2024-07-07 14:04:48.807,1,2.0,False,,False,True
2,0 days 01:02:54.914000,HAM,44,0 days 00:01:31.716000,3.0,1.0,NaT,NaT,0 days 00:00:29.287000,0 days 00:00:37.133000,...,True,Mercedes,0 days 01:01:23.198000,2024-07-07 14:06:20.227,1,2.0,False,,False,True
3,0 days 01:04:26.902000,HAM,44,0 days 00:01:31.988000,4.0,1.0,NaT,NaT,0 days 00:00:29.554000,0 days 00:00:37.258000,...,True,Mercedes,0 days 01:02:54.914000,2024-07-07 14:07:51.943,1,2.0,False,,False,True
4,0 days 01:05:58.579000,HAM,44,0 days 00:01:31.677000,5.0,1.0,NaT,NaT,0 days 00:00:29.469000,0 days 00:00:37.231000,...,True,Mercedes,0 days 01:04:26.902000,2024-07-07 14:09:23.931,1,2.0,False,,False,True

In [9]:
# Telemetry Data
fastestLap_BrGP24 = session_BrGP24.laps.pick_fastest()
tele_BrGP24 = fastestLap_BrGP24.get_telemetry()
tele_BrGP24.head()

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z
2,2024-07-07 15:24:58.857,0 days 02:20:01.828000,,2152.285278,0 days 00:00:00,11458.417187,260.005025,6,100.0,False,0,interpolation,0.022804,0.000004,OnTrack,-1812.638202,1139.400416,1962.954021
3,2024-07-07 15:24:58.956,0 days 02:20:01.927000,,2152.285278,0 days 00:00:00.099000,11145.000000,261.000000,6,100.0,False,0,car,7.233056,0.001238,OnTrack,-1757.529031,1210.855252,1963.370667
4,2024-07-07 15:24:59.052,0 days 02:20:02.023000,,2152.285278,0 days 00:00:00.195000,10850.600000,263.000000,6,100.0,False,0,pos,14.286142,0.002446,OnTrack,-1680.000000,1310.000000,1964.000000
5,2024-07-07 15:24:59.172,0 days 02:20:02.143000,,2152.285278,0 days 00:00:00.315000,10482.600000,265.500000,6,100.0,False,0,pos,23.179391,0.003968,OnTrack,-1561.000000,1461.000000,1965.000000
6,2024-07-07 15:24:59.196,0 days 02:20:02.167000,81,2152.285278,0 days 00:00:00.339000,10409.000000,266.000000,7,100.0,False,0,car,24.966389,0.004274,OnTrack,-1541.317383,1485.864413,1965.166607

In [11]:
# Weather Data
weather_BrGP24 = session_BrGP24.weather_data
weather_BrGP24.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:05.091000,15.9,67.0,991.8,False,28.1,226,2.2
1,0 days 00:01:05.070000,15.9,66.0,991.7,False,27.6,268,1.5
2,0 days 00:02:05.094000,15.9,65.0,991.7,False,27.0,291,1.4
3,0 days 00:03:05.099000,15.9,66.0,991.8,False,27.0,195,1.1
4,0 days 00:04:05.097000,15.9,64.0,991.8,False,31.0,225,1.9

In [12]:
# Pit Stops
pit_BrGP24 = session_BrGP24.laps.dropna(subset=["PitInTime"])
pit_BrGP24.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
26,0 days 01:40:26.353000,HAM,44,0 days 00:01:45.183000,27.0,1.0,NaT,0 days 01:40:20.422000,0 days 00:00:31.477000,0 days 00:00:45.498000,...,True,Mercedes,0 days 01:38:41.170000,2024-07-07 14:43:38.199,1,2.0,False,,False,False
37,0 days 01:59:18.437000,HAM,44,0 days 00:01:37.220000,38.0,2.0,NaT,0 days 01:59:12.470000,0 days 00:00:31.208000,0 days 00:00:40.056000,...,True,Mercedes,0 days 01:57:41.217000,2024-07-07 15:02:38.246,1,2.0,False,,False,False
77,0 days 01:38:50.516000,VER,1,0 days 00:01:41.491000,26.0,1.0,NaT,0 days 01:38:44.599000,0 days 00:00:30.720000,0 days 00:00:43.858000,...,True,Red Bull Racing,0 days 01:37:09.025000,2024-07-07 14:42:06.054,1,5.0,False,,False,False
89,0 days 01:59:23.927000,VER,1,0 days 00:01:35.963000,38.0,2.0,NaT,0 days 01:59:18.092000,0 days 00:00:30.903000,0 days 00:00:39.254000,...,True,Red Bull Racing,0 days 01:57:47.964000,2024-07-07 15:02:44.993,1,3.0,False,,False,False
130,0 days 01:40:23.109000,NOR,4,0 days 00:01:44.806000,27.0,1.0,NaT,0 days 01:40:17.147000,0 days 00:00:32.069000,0 days 00:00:45.057000,...,True,McLaren,0 days 01:38:38.303000,2024-07-07 14:43:35.332,1,1.0,False,,False,False

In [13]:
# Sector Times
sector_BrGP24 = session_BrGP24.laps[["Driver", "LapNumber", "Sector1Time", "Sector2Time", "Sector3Time"]]
sector_BrGP24.head()

,Driver,LapNumber,Sector1Time,Sector2Time,Sector3Time
0,HAM,1.0,NaT,0 days 00:00:37.703000,0 days 00:00:25.484000
1,HAM,2.0,0 days 00:00:29.249000,0 days 00:00:37.314000,0 days 00:00:24.857000
2,HAM,3.0,0 days 00:00:29.287000,0 days 00:00:37.133000,0 days 00:00:25.296000
3,HAM,4.0,0 days 00:00:29.554000,0 days 00:00:37.258000,0 days 00:00:25.176000
4,HAM,5.0,0 days 00:00:29.469000,0 days 00:00:37.231000,0 days 00:00:24.977000

In [14]:
# Race Results
result_BrGP24 = session_BrGP24.results
result_BrGP24.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
44,44,L HAMILTON,HAM,hamilton,Mercedes,27F4D2,mercedes,Lewis,Hamilton,Lewis Hamilton,...,1.0,1,2.0,NaT,NaT,NaT,0 days 01:22:27.059000,Finished,25.0,52.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,2.0,2,4.0,NaT,NaT,NaT,0 days 00:00:01.465000,Finished,18.0,52.0
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,3.0,3,3.0,NaT,NaT,NaT,0 days 00:00:07.547000,Finished,15.0,52.0
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,4.0,4,5.0,NaT,NaT,NaT,0 days 00:00:12.429000,Finished,12.0,52.0
55,55,C SAINZ,SAI,sainz,Ferrari,E80020,ferrari,Carlos,Sainz,Carlos Sainz,...,5.0,5,7.0,NaT,NaT,NaT,0 days 00:00:47.318000,Finished,11.0,52.0

Data Fetching will be performed through following steps.

* Outer loop (Years): Iterates through the years.
* Middle loop (Races): Iterates through each Grand Prix in that year.
* Inner loop (Sessions): Iterates through each session in that particular Grand Prix

In [ ]:
import os
import logging

logging.getLogger("fastf1").setLevel(logging.WARNING)
# Enable the FastF1 cache to prevent redundant network request
cache_dir = "f1_ingest_cache"
os.makedirs(cache_dir, exist_ok=True)
f1.Cache.enable_cache(cache_dir)

# Define ingestion parameters
base_output_dir = "f1_parquet_data"
year = 2025
# Automation Loop
print(f"Processing year: {year}")
try:
    # Fetching the event schedule
    schedule = f1.get_event_schedule(year)
except Exception as e:
    print(f"Could not fetch for year: {year}")

# Loop through each round in season schedule
for _,event in schedule.iterrows():
    round_number = event["RoundNumber"]
    race_name = event["EventName"].replace(" ", "_")

    # Skip pre season testing rounds
    if round_number == 0:
        continue
    if round_number < 16:
        continue

    print(f"Fetching {year} Round {round_number}: {race_name} [Race]")

    try:
        # Load session object
        session = f1.get_session(year, round_number, "S")
        session.load()

        df_laps = session.laps
        df_weather = session.weather_data
        df_results = session.results

        save_dir = os.path.join(
        base_output_dir, str(year), f"Round_{round_number}_{race_name}", "R")
        os.makedirs(save_dir, exist_ok=True)

        # Save as optimized parquet file
        if not df_laps.empty:
            df_laps.to_parquet(os.path.join(save_dir, "laps.parquet"))

        if not df_weather.empty:
            df_weather.to_parquet(os.path.join(save_dir, "weather.parquet"))

        if not df_results.empty:
            # Convert columns to string safely if mixed data types cause Parquet serialization warnings
            df_results = df_results.astype(str)
            df_results.to_parquet(os.path.join(save_dir, "results.parquet"))

    except Exception as e:
        print(f"Error processing {2023} Round {round_number} (R): {e}")
        continue

print("\n--- Data Ingestion Complete! ---")

Processing year: 2025
Fetching 2025 Round 1: Australian_Grand_Prix [Sprint]
Error processing 2023 Round 1 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 2: Chinese_Grand_Prix [Sprint]

core        WARNING 	Driver 44 completed the race distance 00:00.020000 before the recorded end of the session.
_api        WARNING 	Driver  2: Position data is incomplete!
_api        WARNING 	Driver  3: Position data is incomplete!
_api        WARNING 	Driver 11: Position data is incomplete!
_api        WARNING 	Driver 20: Position data is incomplete!
_api        WARNING 	Driver 24: Position data is incomplete!
_api        WARNING 	Driver 77: Position data is incomplete!
_api        WARNING 	Driver  5: Position data is incomplete!
_api        WARNING 	Driver  6: Position data is incomplete!
_api        WARNING 	Driver  7: Position data is incomplete!
_api        WARNING 	Driver 12: Position data is incomplete!
_api        WARNING 	Driver 30: Position data is incomplete!
_api        WARNING 	Driver 87: Position data is incomplete!

Fetching 2025 Round 3: Japanese_Grand_Prix [Sprint]
Error processing 2023 Round 3 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 4: Bahrain_Grand_Prix [Sprint]
Error processing 2023 Round 4 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 5: Saudi_Arabian_Grand_Prix [Sprint]
Error processing 2023 Round 5 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 6: Miami_Grand_Prix [Sprint]

core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '81'
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '27'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '7'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '55'
core        WARNING 	No lap data for driver 16
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 16)
core        WARNING 	Driver 4 completed the race distance 00:00.023000 before the recorded end of the session.
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!

Fetching 2025 Round 7: Emilia_Romagna_Grand_Prix [Sprint]
Error processing 2023 Round 7 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 8: Monaco_Grand_Prix [Sprint]
Error processing 2023 Round 8 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 9: Spanish_Grand_Prix [Sprint]
Error processing 2023 Round 9 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 10: Canadian_Grand_Prix [Sprint]
Error processing 2023 Round 10 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 11: Austrian_Grand_Prix [Sprint]
Error processing 2023 Round 11 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 12: British_Grand_Prix [Sprint]
Error processing 2023 Round 12 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 13: Belgian_Grand_Prix [Sprint]

_api        WARNING 	Failed to align laps for drivers: ['10']
core        WARNING 	Fixed incorrect tyre stint information for driver '10'

Fetching 2025 Round 14: Hungarian_Grand_Prix [Sprint]
Error processing 2023 Round 14 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 15: Dutch_Grand_Prix [Sprint]
Error processing 2023 Round 15 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 16: Italian_Grand_Prix [Sprint]
Error processing 2023 Round 16 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 17: Azerbaijan_Grand_Prix [Sprint]
Error processing 2023 Round 17 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 18: Singapore_Grand_Prix [Sprint]
Error processing 2023 Round 18 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 19: United_States_Grand_Prix [Sprint]

core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!

Fetching 2025 Round 20: Mexico_City_Grand_Prix [Sprint]
Error processing 2023 Round 20 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 21: São_Paulo_Grand_Prix [Sprint]

_api        WARNING 	Driver 11: Car data is incomplete!
_api        WARNING 	Driver 24: Car data is incomplete!
_api        WARNING 	Driver 50: Car data is incomplete!
_api        WARNING 	Driver 77: Car data is incomplete!
_api        WARNING 	Driver  5: Car data is incomplete!
_api        WARNING 	Driver  6: Car data is incomplete!
_api        WARNING 	Driver 12: Car data is incomplete!
_api        WARNING 	Driver 87: Car data is incomplete!
_api        WARNING 	Driver 11: Position data is incomplete!
_api        WARNING 	Driver 24: Position data is incomplete!
_api        WARNING 	Driver 50: Position data is incomplete!
_api        WARNING 	Driver 77: Position data is incomplete!
_api        WARNING 	Driver  5: Position data is incomplete!
_api        WARNING 	Driver  6: Position data is incomplete!
_api        WARNING 	Driver 12: Position data is incomplete!
_api        WARNING 	Driver 87: Position data is incomplete!
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!

Fetching 2025 Round 22: Las_Vegas_Grand_Prix [Sprint]
Error processing 2023 Round 22 (S): Session type 'S' does not exist for this event
Fetching 2025 Round 23: Qatar_Grand_Prix [Sprint]

core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
_api        WARNING 	Driver 11: Position data is incomplete!
_api        WARNING 	Driver 20: Position data is incomplete!
_api        WARNING 	Driver 24: Position data is incomplete!
_api        WARNING 	Driver 77: Position data is incomplete!
_api        WARNING 	Driver  5: Position data is incomplete!
_api        WARNING 	Driver  6: Position data is incomplete!
_api        WARNING 	Driver 12: Position data is incomplete!
_api        WARNING 	Driver 87: Position data is incomplete!

Fetching 2025 Round 24: Abu_Dhabi_Grand_Prix [Sprint]
Error processing 2023 Round 24 (S): Session type 'S' does not exist for this event

--- Data Ingestion Complete! ---